package my_nif;

import hxler.core.Env;
import hxler.core.NifResult;

/**
 * NIF module. Every `@:nif` function becomes a NIF; the wrapper, dispatch,
 * the ErlNifFunc table and ERL_NIF_INIT are generated by the macros.
 */
@:keep
@:headerCode('#include "erl_nif.h"')
@:build(hxler.macros.NifBuilder.build())
class MyNifNif {
	@:nif
	public static function add(a:Int, b:Int):Int {
		return a + b;
	}

	@:nif
	public static function greet(name:String):String {
		return "Hello, " + name + "!";
	}

}
