defmodule Mix.Tasks.Hxler.Gen do
  @moduledoc """
  Generates a Haxe NIF scaffold in the current project.

      mix hxler.gen <nif> --module Elixir.Module [--package <pkg>] [--with-resources]

  Creates `native/<nif>/` in the project root, modelled on the bundled
  `native/math/` example, so that the `use Hxler` macro can compile and load
  it. The Haxe side owns the build (`build.hxml`) and the produced DLL/SO;
  the `use Hxler` macro owns calling the NIF functions.

  Options:

    * `--module <Elixir.Module>` - the Elixir module that will `use Hxler`
      and hold the NIF stubs (required). Written verbatim into
      `Entry.hx` as `"Elixir.<Module>"`.

    * `--package <pkg>` - the Haxe package for the generated classes.
      Defaults to the snake_case of `<nif>`.

    * `--with-resources` - additionally scaffold a resource example
      (`Accum.hx` + `ResourceInit.hx` load callback and `accum_new` /
      `accum_push` / `accum_sum` NIFs).

  Fails if `native/<nif>/` already exists.
  """

  @shortdoc "Scaffolds a Haxe NIF in native/<nif>"

  use Mix.Task

  @doc false
  def run(args) do
    {opts, nif} =
      case OptionParser.parse(args,
             strict: [module: :string, package: :string, with_resources: :boolean]
           ) do
        {opts, [nif], []} when is_binary(nif) ->
          {opts, nif}

        _ ->
          raise "usage: mix hxler.gen <nif> --module Elixir.Module [--package pkg] [--with-resources]"
      end

    module = Keyword.fetch!(opts, :module)
    pkg = Keyword.get(opts, :package, snake(nif))
    with_resources = Keyword.get(opts, :with_resources, false)

    dir = Path.join(["native", nif])

    if File.exists?(dir) do
      Mix.raise("#{dir} already exists; remove it first to regenerate.")
    end

    gen(dir, nif, pkg, module, with_resources)
    note(nif, pkg, module)
  end

  # -- generation ----------------------------------------------------------

  defp gen(dir, nif, pkg, module, with_resources) do
    File.mkdir_p!(Path.join([dir, "source", pkg]))

    write(Path.join(dir, "build.hxml"), build_hxml(pkg))

    write(
      Path.join([dir, "source", pkg, "Main.hx"]),
      main_hx(pkg)
    )

    write(
      Path.join([dir, "source", pkg, "#{cls(nif)}Nif.hx"]),
      nif_hx(pkg, cls(nif), with_resources)
    )

    if with_resources do
      write(Path.join([dir, "source", pkg, "Accum.hx"]), accum_hx(pkg))
      write(Path.join([dir, "source", pkg, "ResourceInit.hx"]), resource_init_hx(pkg))
    end

    write(
      Path.join([dir, "source", pkg, "Entry.hx"]),
      entry_hx(pkg, nif, module, with_resources)
    )
  end

  # -- templates -----------------------------------------------------------

  defp build_hxml(pkg) do
    """
    -cp source
    -main #{pkg}.Main
    --cpp bin/cpp
    -D HXCPP_M64
    -D dll_link
    -D no_shared_libs
    """
  end

  defp main_hx(pkg) do
    """
    package #{pkg};

    import #{pkg}.Entry;

    /**
     * Dummy main (DLL build needs a valid -main; the NIF entrypoint lives in
     * the generated glue of #{pkg}.Entry).
     */
    @:keep
    class Main {
    \tpublic static function main() {}
    }
    """
  end

  defp nif_hx(pkg, cls, with_resources) do
    resources =
      if with_resources do
        """

        \t// ---- resources ----
        \t@:nif
        \tpublic static function accumNew():hxler.core.ResourceArc<#{pkg}.Accum> {
        \t\treturn hxler.core.ResourceArc.make(new #{pkg}.Accum());
        \t}

        \t@:nif
        \tpublic static function accumPush(arc:hxler.core.ResourceArc<#{pkg}.Accum>, v:Int):Void {
        \t\tarc.get().push(v);
        \t}

        \t@:nif
        \tpublic static function accumSum(arc:hxler.core.ResourceArc<#{pkg}.Accum>):Int {
        \t\treturn arc.get().sum();
        \t}
        """
      else
        ""
      end

    """
    package #{pkg};

    import hxler.core.Env;
    import hxler.core.NifResult;

    /**
     * NIF module. Every `@:nif` function becomes a NIF; the wrapper, dispatch,
     * the ErlNifFunc table and ERL_NIF_INIT are generated by the macros.
     */
    @:keep
    @:headerCode('#include "erl_nif.h"')
    @:build(hxler.macros.NifBuilder.build())
    class #{cls}Nif {
    \t@:nif
    \tpublic static function add(a:Int, b:Int):Int {
    \t\treturn a + b;
    \t}

    \t@:nif
    \tpublic static function greet(name:String):String {
    \t\treturn "Hello, " + name + "!";
    \t}
    #{resources}
    }
    """
  end

  defp accum_hx(pkg) do
    """
    package #{pkg};

    /**
     * Example resource payload: mutable native state between NIF calls.
     */
    @:keep
    class Accum implements hxler.core.Resource {
    \tpublic var items:Array<Int> = [];

    \tpublic function new() {}

    \tpublic function push(v:Int):Void {
    \t\titems.push(v);
    \t}

    \tpublic function sum():Int {
    \t\tvar acc = 0;
    \t\tfor (v in items) acc += v;
    \t\treturn acc;
    \t}
    }
    """
  end

  defp resource_init_hx(pkg) do
    """
    package #{pkg};

    /**
     * Haxe load callback for the NIF: registers the resource types.
     * Passed as the third argument to EntryBuilder.build.
     */
    @:keep
    class ResourceInit {
    \tpublic static function load(env:hxler.core.Env, _loadInfo:hxler.core.Term):Bool {
    \t\treturn env.registerResource(#{pkg}.Accum);
    \t}
    }
    """
  end

  defp entry_hx(pkg, nif, module, with_resources) do
    load =
      if with_resources do
        ", \"#{pkg}.ResourceInit.load\""
      else
        ""
      end

    """
    package #{pkg};

    /**
     * Generated glue: ErlNifFunc table, trampolines, boot, resource callbacks
     * and ERL_NIF_INIT for "Elixir.#{module}".
     */
    @:keep
    @:headerCode('#include "erl_nif.h"')
    @:buildXml('<files id="haxe">
    \t<compilerflag value="-I${hxler_erts_include}" />
    \t<compilerflag value="-I${hxler_sdk_include}" />
    </files>
    <files id="__main__">
    \t<compilerflag value="-I${hxler_erts_include}" />
    \t<compilerflag value="-I${hxler_sdk_include}" />
    </files>')
    @:build(hxler.macros.EntryBuilder.build(["#{pkg}.#{cls(nif)}Nif"], "Elixir.#{module}"#{load}))
    class Entry {
    }
    """
  end

  # -- helpers -------------------------------------------------------------

  defp write(path, content) do
    File.write!(path, content)
    Mix.shell().info("  create  #{path}")
  end

  defp note(nif, pkg, module) do
    Mix.shell().info("""
    Generated native/#{nif}. Next steps:

      1. Add the module that loads it (stubs in snake_case, one per @:nif):

             defmodule #{module} do
               use Hxler, otp_app: :#{otp_app_hint()}, nif: :#{nif}
               def add(_a, _b), do: :erlang.nif_error(:nif_not_loaded)
               def greet(_name), do: :erlang.nif_error(:nif_not_loaded)
               ...
               def hxler_init, do: :ok
             end

      2. mix compile   # builds native/#{nif} -> priv/native/#{nif}.so/.dll
      3. mix test      # NIF loaded via @on_load

    Haxe package used: #{pkg}
    """)
  end

  defp otp_app_hint do
    Mix.Project.config()[:app] || "your_app"
  end

  defp snake(s) do
    # camelCase/acronym -> snake_case (e.g. MyNIF -> my_nif, my_nif -> my_nif)
    s
    |> String.replace(~r/([A-Z]+)([A-Z][a-z])/, "\\1_\\2")
    |> String.replace(~r/([a-z0-9])([A-Z])/, "\\1_\\2")
    |> String.downcase()
  end

  defp cls(s) do
    s
    |> Macro.camelize()
  end
end
