defmodule Example.MyNif do
  @moduledoc """
  Consumer example: loads the `native/my_nif` Haxe NIF generated by
  `mix hxler.gen my_nif --module Example.MyNif`.

  Stubs must be snake_case — the NIF name is derived from the `@:nif`
  function name by `hxler.macros.NifBuilder` (`add` -> `add`,
  `greet` -> `greet`).
  """

  use Hxler, otp_app: :example, nif: :my_nif

  def add(_a, _b), do: :erlang.nif_error(:nif_not_loaded)
  def greet(_name), do: :erlang.nif_error(:nif_not_loaded)
end
