defmodule Example.MyNif do
  @moduledoc """
  Consumer example: loads the `native/my_nif` Haxe NIF generated by
  `mix hxler.gen my_nif --module Example.MyNif`.

  No stubs are declared here — `use Hxler` auto-generates them from the
  build manifest (`hxler_manifest.txt`).
  """

  use Hxler, otp_app: :example, nif: :my_nif
end
