package math;

import hxler.core.Env;
import hxler.core.EnvKind;
import hxler.core.Term;
import hxler.core.NifError;
import hxler.core.NifResult;
import hxler.core.NifReturn;

/**
 * Phase 4 NIF module: functions declared with @:nif; wrappers, dispatch,
 * the ErlNifFunc table and ERL_NIF_INIT are generated by the macros.
 */
@:keep
@:headerCode('#include "erl_nif.h"')
@:build(hxler.macros.NifBuilder.build())
class MathNif {
	// plain types; env optional first param
	@:nif
	public static function add(a:Int, b:Int):Int {
		return a + b;
	}

	@:nif
	public static function sum64(a:haxe.Int64, b:haxe.Int64):haxe.Int64 {
		return haxe.Int64.add(a, b);
	}

	@:nif(name = "greet")
	public static function greet(name:String):String {
		return "Hello, " + name + "!";
	}

	// overload: same NIF name, different arity -> ERL_NIF exports
	// same_name/1 and same_name/2 (Haxe itself can't overload by arity).
	@:nif(name = "same_name")
	public static function sameName1(a:Int):Int {
		return a * 10;
	}

	@:nif(name = "same_name")
	public static function sameName2(a:Int, b:Int):Int {
		return a * 10 + b;
	}

	@:nif(schedule = "dirty_cpu")
	public static function fib(n:haxe.Int64):haxe.Int64 {
		var a:haxe.Int64 = 0;
		var b:haxe.Int64 = 1;
		var i:haxe.Int64 = 0;
		while (i < n) {
			var t = haxe.Int64.add(a, b);
			a = b;
			b = t;
			i = haxe.Int64.add(i, haxe.Int64.ofInt(1));
		}
		return a;
	}

	// NifResult-returning function: {:ok, v} | {:error, reason};
	// explicit Env first param (not counted in arity).
	@:nif
	public static function safeDiv(env:hxler.core.Env, a:Int, b:Int):hxler.core.NifResult<hxler.core.Term> {
		if (b == 0) {
			return Error(NifError.Term(env.atom("zero_division")));
		}
		return Ok(env.int(Std.int(a / b)));
	}

	// raw function: full manual control
	@:nif(name = "atom_text", arity = 1)
	public static function atomText(env:hxler.nif.raw.ErlNifEnv, argc:Int, argv:cpp.Pointer<hxler.nif.raw.NifTerm>):hxler.nif.raw.NifTerm {
		var e = new Env(env, EnvKind.ProcessBound);
		var t = new Term(e, argv[0]);
		var a = t.asAtom();
		if (a == null) {
			return hxler.core.NifReturn.errorTerm(e, NifError.BadArg);
		}
		return e.binaryFromBytes(haxe.io.Bytes.ofString(a.toString())).raw;
	}

	// lists/maps/bool/float/option through macro dispatch
	@:nif
	public static function listSum(items:Array<Int>):Int {
		var acc = 0;
		for (v in items) {
			acc += v;
		}
		return acc;
	}

	@:nif
	public static function mapSum(m:Map<String, Int>):Int {
		var acc = 0;
		for (v in m) {
			acc += v;
		}
		return acc;
	}

	@:nif
	public static function both(b:Bool, f:Float):Float {
		return b ? f * 2.0 : f;
	}

	@:nif
	public static function optOr42(v:Null<Int>):Int {
		return v == null ? 42 : v;
	}

	// ---- phase 5: resources ----

	@:nif
	public static function accumNew():hxler.core.ResourceArc<Accum> {
		return hxler.core.ResourceArc.make(new Accum());
	}

	@:nif
	public static function accumPush(arc:hxler.core.ResourceArc<Accum>, v:Int):Void {
		arc.get().push(v);
	}

	@:nif
	public static function accumSum(arc:hxler.core.ResourceArc<Accum>):Int {
		return arc.get().sum();
	}

	@:nif
	public static function accumLen(arc:hxler.core.ResourceArc<Accum>):Int {
		return arc.get().items.length;
	}

	@:nif
	public static function isAccum(t:hxler.core.Term):Bool {
		return t.tryGetResource(Accum) != null;
	}
}

